const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const Store = require('../homebridge-ui/config-store');
const M = require('../homebridge-ui/public/config-model');

test('first save on a fresh Homebridge keeps its bridge identity and other plugins', t => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'myhome-clean-'));
    t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
    const file = path.join(dir, 'config.json');
    const bridge = { name: 'New site', username: 'AA:BB:CC:DD:EE:FF', pin: '031-45-154' };
    fs.writeFileSync(file, JSON.stringify({ bridge, platforms: [{ platform: 'config' }] }));
    const store = new Store(file), before = store.read();
    const blocks = M.load(before.blocks);
    blocks[0].ipaddress = '192.0.2.10';
    store.save({ blocks, revision: before.revision });
    const saved = JSON.parse(fs.readFileSync(file));
    assert.deepEqual(saved.bridge, bridge);
    assert.equal(saved.platforms[0].platform, 'config');
    assert.deepEqual(saved.platforms[1].devices, []);
    assert.equal(saved.platforms.length, 2);
});
test('reads both aliases and saves migration without losing unrelated configuration', t => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'myhome-'));
    t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
    const file = path.join(dir, 'config.json');
    const other = { platform: 'config', name: 'Config', custom: true };
    const original = { bridge: { name: 'Home' }, platforms: [other, { platform: M.HAP, ipaddress: 'gateway', devices: [{ accessory: 'MHRelay', name: 'Test', address: '0/0/3' }] }, { platform: M.MATTER, address: '0/0/3', enabled: true }] };
    fs.writeFileSync(file, JSON.stringify(original));
    const store = new Store(file), read = store.read();
    assert.equal(read.blocks.length, 2);
    assert.deepEqual(JSON.parse(fs.readFileSync(file)), original);
    store.save({ blocks: M.load(read.blocks), revision: read.revision });
    const saved = JSON.parse(fs.readFileSync(file));
    assert.deepEqual(saved.platforms[0], other);
    assert.deepEqual(saved.bridge, original.bridge);
    assert.equal(saved.platforms.length, 3);
    assert.equal(saved.platforms[1].devices[0].matter, true);
    assert.equal(saved.platforms[2].mode, 'configured');
    assert.throws(() => store.save({ blocks: read.blocks, revision: read.revision }), /mudou/);
    assert.throws(() => store.save({ blocks: [other], revision: store.read().revision }), /Somente/);
    assert.equal(fs.readdirSync(dir).filter(n => n.includes('backup')).length, 1);
});
